pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest --junitxml=test-reports/results.xml'
            }
        }
    }
    post {
        always {
            junit 'test-reports/results.xml'
        }
    }
}
